import { VoicePreset, AudioSettings } from '../types/tts';

export const DEFAULT_AUDIO_SETTINGS: AudioSettings = {
  speed: 1.05, // Slightly perky for TikTok
  pitch: 4, // +4 semitones for authentic sweet baby pitch
  formantBoost: 7, // Emphasize child oral resonance
  bassCut: 6, // Cut low frequencies
  trebleCrisp: 5, // Crisp treble
  reverbAmount: 0, // Clean dry voice (no reverb/echo)
  echoDelay: 0,
  volume: 100,

  // Advanced Equalizer Defaults (optimized for crisp clean voice)
  equalizer: {
    f60: -4, // Cut sub-rumble
    f250: -1, // Clean low-mid
    f1k: 2, // Warm speech body
    f4k: 4, // Baby oral brightness
    f12k: 3, // Sparkle air
  },

  // Dry Studio Defaults (Không vang vọng)
  reverb: {
    type: 'none',
    decay: 0,
    preDelay: 0,
    wet: 0,
    highDamp: 0,
  },

  // Background Music Defaults
  bgm: {
    enabled: false,
    trackId: 'cute_playtime',
    volume: 24, // 24% background presence
    autoDucking: true, // Auto ducking when baby voice is speaking
    duckingAmount: 0.22,
    loop: true,
  },

  // Normalization & Studio Mastering Defaults
  normalization: {
    enabled: true,
    targetPeakDb: -1.0, // Industry standard -1.0 dBFS true peak
    compressorRatio: 3.0,
    deEsser: true,
    limiter: true,
  },

  exportWithBgm: true,
};

export const VOICE_PRESETS: VoicePreset[] = [
  // ==========================================
  // 1. DỊCH VỤ GIỌNG NÓI BING (MICROSOFT BING)
  // ==========================================
  {
    id: 'bing_hoaimy',
    name: 'Hoài My',
    shortDesc: 'Giọng nữ miền Bắc truyền cảm, ấm áp, chuẩn phát thanh podcast & audiobook',
    gender: 'female',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '🎙️',
    tag: 'Bing Nữ',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Warm, expressive northern Vietnamese female voice (Hoai My style), natural, articulate, soothing storytelling and podcast narrator in Vietnamese.',
  },
  {
    id: 'bing_namminh',
    name: 'Nam Minh',
    shortDesc: 'Giọng nam miền Bắc trầm ấm, đĩnh đạc, bản lĩnh và truyền cảm hứng',
    gender: 'male',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '🤵',
    tag: 'Bing Nam',
    geminiVoice: 'Charon',
    defaultPitch: -1,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Deep, resonant, warm northern Vietnamese male voice (Nam Minh style), mature, calm, authoritative broadcast quality in Vietnamese.',
  },
  {
    id: 'bing_andrew',
    name: 'Andrew',
    shortDesc: 'Giọng nam hiện đại, phát âm rõ ràng, nhịp điệu tự nhiên chuẩn quốc tế',
    gender: 'male',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '👨‍💼',
    tag: 'Bing Nam',
    geminiVoice: 'Fenrir',
    defaultPitch: 0,
    defaultSpeed: 1.02,
    defaultFormant: 0,
    stylePrompt: 'Modern, clear, articulate male narrator (Andrew style), engaging, friendly and confident in Vietnamese.',
  },
  {
    id: 'bing_ava',
    name: 'Ava',
    shortDesc: 'Giọng nữ trẻ trung, thân thiện, dễ nghe và cực kỳ tự nhiên',
    gender: 'female',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '👩‍🦰',
    tag: 'Bing Nữ',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 1.04,
    defaultFormant: 1,
    stylePrompt: 'Natural, cheerful, bright young female narrator (Ava style), conversational and pleasant in Vietnamese.',
  },
  {
    id: 'bing_brian',
    name: 'Brian',
    shortDesc: 'Giọng nam sâu lắng, thích hợp làm video phóng sự, phim tài liệu, tóm tắt sách',
    gender: 'male',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '🧔',
    tag: 'Bing Nam',
    geminiVoice: 'Charon',
    defaultPitch: -2,
    defaultSpeed: 0.98,
    defaultFormant: 0,
    stylePrompt: 'Deep, thoughtful, narrative documentary male voice (Brian style), measured, compelling storytelling in Vietnamese.',
  },
  {
    id: 'bing_emma',
    name: 'Emma',
    shortDesc: 'Giọng nữ tươi vui, năng động, phong cách vlog đời sống và tin tức giới trẻ',
    gender: 'female',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '👱‍♀️',
    tag: 'Bing Nữ',
    geminiVoice: 'Zephyr',
    defaultPitch: 1,
    defaultSpeed: 1.05,
    defaultFormant: 2,
    stylePrompt: 'Youthful, charming, upbeat female voice (Emma style), bright, engaging lifestyle vlog tone in Vietnamese.',
  },
  {
    id: 'bing_seraphina',
    name: 'Seraphina',
    shortDesc: 'Giọng nữ quý phái, êm ái, thanh tao, phù hợp video kể chuyện & triết lý',
    gender: 'female',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '👑',
    tag: 'Bing Nữ',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 0.95,
    defaultFormant: 0,
    stylePrompt: 'Sophisticated, elegant, poetic female voice (Seraphina style), smooth, velvety, storytelling in Vietnamese.',
  },
  {
    id: 'bing_florian',
    name: 'Florian',
    shortDesc: 'Giọng nam đĩnh đạc, rành mạch, tốc độ ổn định cho video hướng dẫn',
    gender: 'male',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '🧑‍💻',
    tag: 'Bing Nam',
    geminiVoice: 'Fenrir',
    defaultPitch: 0,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Distinctive, scholarly, articulate male voice (Florian style), crisp, well-paced explanation in Vietnamese.',
  },
  {
    id: 'bing_vivienne',
    name: 'Vivienne',
    shortDesc: 'Giọng nữ ngọt ngào, dịu dàng, lãng mạn cho thơ ca và truyện tình cảm',
    gender: 'female',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '🌸',
    tag: 'Bing Nữ',
    geminiVoice: 'Kore',
    defaultPitch: 1,
    defaultSpeed: 0.98,
    defaultFormant: 2,
    stylePrompt: 'Sweet, melodious, gentle female voice (Vivienne style), pleasant, charming and warm in Vietnamese.',
  },
  {
    id: 'bing_remy',
    name: 'Remy',
    shortDesc: 'Giọng nam nhẹ nhàng, thư giãn, hiện đại cho video review công nghệ',
    gender: 'male',
    category: 'bing',
    provider: 'Dịch vụ giọng nói Bing',
    icon: '🎧',
    tag: 'Bing Nam',
    geminiVoice: 'Puck',
    defaultPitch: 0,
    defaultSpeed: 1.02,
    defaultFormant: 0,
    stylePrompt: 'Calm, friendly, relaxed male voice (Remy style), easygoing, modern conversational tone in Vietnamese.',
  },

  // ==========================================
  // 2. DỊCH VỤ GIỌNG NÓI CỦA GOOGLE CLOUD
  // ==========================================
  {
    id: 'google_nu_1',
    name: 'Nữ 1',
    shortDesc: 'Google Cloud Wavenet Nữ chuẩn, rõ ràng, phong cách dẫn truyền hình chuẩn mực',
    gender: 'female',
    category: 'google_cloud',
    provider: 'Dịch vụ giọng nói của Google Cloud',
    icon: '👩',
    tag: 'Google Cloud',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Google Cloud Standard Female 1, crystal clear, professional, balanced pitch, broadcast quality in Vietnamese.',
  },
  {
    id: 'google_nu_2',
    name: 'Nữ 2',
    shortDesc: 'Google Cloud Nữ cao trong trẻo, hoạt ngôn, thích hợp video thương mại quảng cáo',
    gender: 'female',
    category: 'google_cloud',
    provider: 'Dịch vụ giọng nói của Google Cloud',
    icon: '✨',
    tag: 'Google Cloud',
    geminiVoice: 'Zephyr',
    defaultPitch: 1,
    defaultSpeed: 1.05,
    defaultFormant: 2,
    stylePrompt: 'Google Cloud Standard Female 2, bright, higher pitch, articulate, commercial narration in Vietnamese.',
  },
  {
    id: 'google_nu_3',
    name: 'Nữ 3',
    shortDesc: 'Google Cloud Neural2 Nữ thế hệ mới, mượt mà, cảm xúc sâu lắng',
    gender: 'female',
    category: 'google_cloud',
    provider: 'Dịch vụ giọng nói của Google Cloud',
    icon: '🌟',
    tag: 'Google Cloud',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 0.98,
    defaultFormant: 1,
    stylePrompt: 'Google Cloud Neural2 Female 3, expressive, smooth natural cadence, warm and inviting in Vietnamese.',
  },
  {
    id: 'google_nam_1',
    name: 'Nam 1',
    shortDesc: 'Google Cloud Nam phát thanh tin tức, giọng trầm, uy quyền và đáng tin cậy',
    gender: 'male',
    category: 'google_cloud',
    provider: 'Dịch vụ giọng nói của Google Cloud',
    icon: '🎙️',
    tag: 'Google Cloud',
    geminiVoice: 'Charon',
    defaultPitch: -1,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Google Cloud Standard Male 1, deep, authoritative, clear pronunciation, news broadcast in Vietnamese.',
  },
  {
    id: 'google_nam_2',
    name: 'Nam 2',
    shortDesc: 'Google Cloud Nam trung âm ấm, tự nhiên, gần gũi cho bài giảng và giới thiệu sản phẩm',
    gender: 'male',
    category: 'google_cloud',
    provider: 'Dịch vụ giọng nói của Google Cloud',
    icon: '👨',
    tag: 'Google Cloud',
    geminiVoice: 'Fenrir',
    defaultPitch: 0,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Google Cloud Standard Male 2, friendly, warm baritone, engaging narrator in Vietnamese.',
  },
  {
    id: 'google_nam_3',
    name: 'Nam 3',
    shortDesc: 'Google Cloud Neural2 Nam năng động, nhịp nói hoạt bát, phong cách hiện đại',
    gender: 'male',
    category: 'google_cloud',
    provider: 'Dịch vụ giọng nói của Google Cloud',
    icon: '🔥',
    tag: 'Google Cloud',
    geminiVoice: 'Zephyr',
    defaultPitch: 0,
    defaultSpeed: 1.04,
    defaultFormant: 0,
    stylePrompt: 'Google Cloud Neural2 Male 3, natural, dynamic, conversational modern male voice in Vietnamese.',
  },

  // ==========================================
  // 3. GIỌNG CHỊ GOOGLE
  // ==========================================
  {
    id: 'chi_google',
    name: 'Chị Google',
    shortDesc: 'Giọng đọc quốc dân huyền thoại, tròn vành rõ chữ, hài hước viral triệu view',
    gender: 'female',
    category: 'chi_google',
    provider: 'Giọng Chị Google',
    icon: '📢',
    tag: 'Quốc Dân',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Iconic legendary Vietnamese Chi Google voice, clear, rhythmic, humorous, iconic TikTok narration style in Vietnamese.',
  },

  // ==========================================
  // 4. GIỌNG ĐỌC CỦA TIKTOK
  // ==========================================
  {
    id: 'tiktok_nu_1',
    name: 'Nữ 1',
    shortDesc: 'Giọng nữ review TikTok triệu view, cuốn hút, bắt tai và nhịp điệu nhanh',
    gender: 'female',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '👩‍🦰',
    tag: 'TikTok Viral',
    geminiVoice: 'Kore',
    defaultPitch: 1,
    defaultSpeed: 1.08,
    defaultFormant: 3,
    stylePrompt: 'TikTok Female 1, viral video narrator, engaging, fast-paced, entertaining review tone in Vietnamese.',
  },
  {
    id: 'tiktok_nam_1',
    name: 'Nam 1',
    shortDesc: 'Giọng nam review phim kịch tính, tóm tắt truyện, cuốn hút người nghe',
    gender: 'male',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '🎬',
    tag: 'TikTok Review',
    geminiVoice: 'Charon',
    defaultPitch: -1,
    defaultSpeed: 1.05,
    defaultFormant: 0,
    stylePrompt: 'TikTok Male 1, dramatic movie recap narrator, cinematic, tension-building recap voice in Vietnamese.',
  },
  {
    id: 'tiktok_nu_2',
    name: 'Nữ 2',
    shortDesc: 'Giọng nữ TikTok ngọt ngào, tươi tắn, siêu dễ thương cho vlog hàng ngày',
    gender: 'female',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '🎀',
    tag: 'TikTok Cute',
    geminiVoice: 'Zephyr',
    defaultPitch: 2,
    defaultSpeed: 1.06,
    defaultFormant: 4,
    stylePrompt: 'TikTok Female 2, cute, sweet, vibrant young girl review tone, cheerful and playful in Vietnamese.',
  },
  {
    id: 'tiktok_baby_cute',
    name: 'Em Bé TikTok Cute',
    shortDesc: 'Giọng bé gái 3-4 tuổi ngọt ngào, đáng yêu viral triệu view',
    gender: 'child',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '👶',
    tag: 'Trending Baby',
    geminiVoice: 'Puck',
    defaultPitch: 5,
    defaultSpeed: 1.08,
    defaultFormant: 8,
    stylePrompt: 'Adorable 4-year-old baby girl voice, cheerful, very high-pitched cute toddler, sweet and playful, viral TikTok cute kid sound in Vietnamese.',
  },
  {
    id: 'tiktok_baby_boy',
    name: 'Bé Trai Tinh Nghịch',
    shortDesc: 'Giọng bé trai hiếu động, lém lỉnh, đầy năng lượng',
    gender: 'child',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '👦',
    tag: 'Vui nhộn',
    geminiVoice: 'Puck',
    defaultPitch: 4,
    defaultSpeed: 1.1,
    defaultFormant: 6,
    stylePrompt: 'Cute 4-year-old energetic baby boy voice, enthusiastic, slightly mischievous, high-pitched toddler style in Vietnamese.',
  },
  {
    id: 'tiktok_fairy_tale',
    name: 'Bé Kể Chuyện Cổ Tích',
    shortDesc: 'Giọng em bé êm dịu, ngọt lịm, ấm áp truyền cảm',
    gender: 'female',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '🧚‍♀️',
    tag: 'Truyện ngủ',
    geminiVoice: 'Kore',
    defaultPitch: 3,
    defaultSpeed: 0.95,
    defaultFormant: 5,
    stylePrompt: 'Innocent sweet child storytelling voice, gentle, lovable, speaking clearly like a bedtime fairytale baby in Vietnamese.',
  },
  {
    id: 'tiktok_sweet_girl',
    name: 'Bé Gái Nũng Nịu',
    shortDesc: 'Em gái nhỏ xin xỏ, giọng nũng nịu tan chảy trái tim',
    gender: 'female',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '👧',
    tag: 'Siêu Cưng',
    geminiVoice: 'Kore',
    defaultPitch: 6,
    defaultSpeed: 1.02,
    defaultFormant: 7,
    stylePrompt: 'Sweet little preschool girl asking or explaining something adorably, affectionate and cute viral TikTok style in Vietnamese.',
  },
  {
    id: 'tiktok_smart_kid',
    name: 'MC Nhí Thông Thái',
    shortDesc: 'Giọng bé 6 tuổi dõng dạc, rõ ràng, hoạt ngôn',
    gender: 'child',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '🎓',
    tag: 'Khám phá',
    geminiVoice: 'Zephyr',
    defaultPitch: 2,
    defaultSpeed: 1.0,
    defaultFormant: 4,
    stylePrompt: 'Bright confident 6-year-old kid narrator, energetic, clear articulation, cheerful in Vietnamese.',
  },
  {
    id: 'tiktok_chipmunk_baby',
    name: 'Sóc Chuột Chipmunk',
    shortDesc: 'Tông cực cao, hài hước, biến hóa vui nhộn cho video troll',
    gender: 'child',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '🐿️',
    tag: 'Hài hước',
    geminiVoice: 'Puck',
    defaultPitch: 8,
    defaultSpeed: 1.15,
    defaultFormant: 9,
    stylePrompt: 'Ultra high-pitched cartoon baby chipmunk voice, bubbly, bouncy, hilarious and super cute in Vietnamese.',
  },
  {
    id: 'tiktok_female_genz',
    name: 'Cô Gái Gen Z Năng Động',
    shortDesc: 'Nói nhanh, hóm hỉnh, bắt trend năng động cho video ngắn',
    gender: 'female',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '✨',
    tag: 'Gen Z Trendy',
    geminiVoice: 'Zephyr',
    defaultPitch: 1,
    defaultSpeed: 1.12,
    defaultFormant: 3,
    stylePrompt: 'Trendy enthusiastic young Vietnamese Gen Z girl, fast-paced, bright, witty, cheerful viral TikTok tone in Vietnamese.',
  },
  {
    id: 'tiktok_female_mc',
    name: 'Nữ MC Dẫn Chương Trình',
    shortDesc: 'Giọng dẫn thanh lịch, chuẩn mực, lưu loát và truyền cảm hứng',
    gender: 'female',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '👑',
    tag: 'Chuyên Nghiệp',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Professional Vietnamese female presenter and news host, elegant, crystal clear articulation, confident and trustworthy in Vietnamese.',
  },
  {
    id: 'tiktok_female_sweet_asmr',
    name: 'Nữ Êm Dịu / Thư Giãn',
    shortDesc: 'Giọng thì thầm nhẹ nhàng, êm ái, chữa lành cho podcast & ru ngủ',
    gender: 'female',
    category: 'tiktok',
    provider: 'Giọng đọc của TikTok',
    icon: '🌙',
    tag: 'Chữa Lành',
    geminiVoice: 'Kore',
    defaultPitch: -1,
    defaultSpeed: 0.92,
    defaultFormant: 2,
    stylePrompt: 'Gentle soft-spoken Vietnamese female voice, soothing, intimate, relaxing bedtime and lifestyle storyteller in Vietnamese.',
  },

  // ==========================================
  // 5. GIỌNG CỦA TRÌNH DUYỆT
  // ==========================================
  {
    id: 'browser_an',
    name: 'Microsoft An - Vietnamese (Vietnam)',
    shortDesc: 'Giọng đọc tiếng Việt tích hợp trong trình duyệt Microsoft Edge / Windows',
    gender: 'female',
    category: 'browser',
    provider: 'Giọng của trình duyệt (Sẽ bị ngừng khi rời khỏi màn hình do bảo mật của trình duyệt)',
    icon: '🌐',
    tag: 'Trình duyệt',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Clear Vietnamese browser voice, standard natural reading in Vietnamese.',
    isBrowserVoice: true,
  },
  {
    id: 'browser_system',
    name: 'Giọng Hệ Thống Trình Duyệt',
    shortDesc: 'Sử dụng công cụ giọng nói cục bộ trên trình duyệt của máy bạn',
    gender: 'female',
    category: 'browser',
    provider: 'Giọng của trình duyệt (Sẽ bị ngừng khi rời khỏi màn hình do bảo mật của trình duyệt)',
    icon: '💻',
    tag: 'System TTS',
    geminiVoice: 'Kore',
    defaultPitch: 0,
    defaultSpeed: 1.0,
    defaultFormant: 0,
    stylePrompt: 'Default system assistant voice, clear, articulate in Vietnamese.',
    isBrowserVoice: true,
  },
];
